const senhaCorreta = "eu"; 

function verificarSenha() {
  const senhaDigitada = document.getElementById("senha").value;
  const erro = document.getElementById("erro");

  if (senhaDigitada === senhaCorreta) {
    document.getElementById("login-container").style.display = "none";
    document.getElementById("conteudo").style.display = "block";
    gerarLista();
  } else {
    erro.textContent = "Como que você não sabe a senha?";
  }
}

function gerarLista() {
  const lista = document.getElementById("lista-carinho");

  const coisasQueGosto = [
    "Eu amo as suas brincadeiras",
    "Eu amo os seus dentes",
    "Eu amo como você planeja o nosso futuro",
    "Eu amo como você esta em todos os meus planos",
    "Eu amo confiar em você e poder contar tudo pra oc",
    "Eu amo passar cada segundo do meu dia pesando em você",
    "Eu amo estar com saudade segundos depois de me despedir você",
    "Eu amo seu corte na orelha, acho ele legal",
    "Eu amo quando você tenta me irritar",
    "Eu amo o seu jeito bobo",
    "Eu amo quando você me provoca",
    "Eu amo quando você diz que vai lamber meu pau olhando pra mim",
    "Eu amo a sua língua",
    "Eu amo ter você",
    "Eu amo ser seu",
    "Eu amo a sua beleza maior que a de qualquer modelo",
    "Eu amo te fazer rir",
    "Eu amo como sempre abro um sorriso quando te escuto",
    "Eu amo como depois de tanto tempo sou completamente apaixonado por você",
    "Eu amo ficar bobo com você, rs.",
    "Eu amo como você arruma o cabelo",
    "Eu amo como você olha pra mim quando ligo a cam",
    "Eu amo cada segundo que eu passo contigo mesmo de longe",
    "Eu amo falar as coisas que amo em você",
    "Eu amo a sua capacidade de me fazer rir em qualquer situação",
    "Eu amo a sua ironia",
    "Eu amo como você me respeita",
    "Eu amo respeitar e admirar você",
    "Eu amo como você me tornou romântico",
    "Eu amo como te faço ficar sem argumentos",
    "Eu amo como você perde a linha hhihihihihi",
    "Eu amo a segurança que você me transmite",
    "Eu amo a sua demora pra se arrumar",
    "Eu amo a sua vaidade",
    "Eu amo como você me ama até na TPM",
    "Eu amo quando você faz a coisa que eu falo que eu amo (você entendeu rs)",
    "Eu amo pedir sua opinião pra tudo",
    "Eu amo como você pede minha opinião pra tudo",
    "Eu amo como você é o meu futuro",
    "Eu amo como você me acha bonito mesmo desarrumado",
    "Eu amo os seus dedos",
    "Eu amo os seus baby dolls...",
    "Eu amo como você admite seus erros",
    "Eu amo como você pede desculpa quando está errado",
    "Eu amo como você às vezes fala nada com nada",
    "Eu amo como nunca quero deixá-la ir",
    "Eu amo como odeio ficar longe de você",
    "Eu amo meu medo de te perder",
    "Eu amo sentir ciúme de você",
    "Eu amo te dar carinho",
    "Eu amo como oc eh a menininha do papai",
    "Eu amo as suas piadas sem graça",
    "amo jogar com você",
    "amo nossos momentos em call",
    "amo sua forma de cuidar de você",
    "amo a sua fidelidade mb",	
    "amo a sua lealdade",
    "Eu te amo porque até eu me amo mais depois que te conheci",
    "Eu te amo porque você sempre quer ser melhor e me dar o melhor",
    "Eu te amo porque juntos fazemos loucuras maravilhosas",
    "Eu te amo porque sim",
    "Eu te amo porque você me envia os melhores stickers e figurinhas",
    "eu amo pensar em você e no seu jeitinho e pensar: encontrei",
    "eu te amo pq oc faz eu rir ate doer as bochechas",
    "amo seu jeito de ser",
    "te amo por você ser a melhor esposa do mundo"/
    "te amo por você ser a melhor namorada do mundo",
    "amo quando você fala sobre ter filhos",	
    "amo o quanto você se importa com nossa relação",
    "amo o quanto você se esforça para me agradar",
    "amo quando você demonstra oque sente por mim",
    "amo seu narizinho fofinho'",
    "amo ver vc sem oculos",
    "seu narizinho lindinho meu amor",
    "o formato dos seus labios que me atraem tanto...",
    "seu sorriso bobinho hihihihihi",
    "todas coisas que sairem de você exceto o milho... ",
    "eu amo seus defeitos amor, todinhos",
    "a suas marcas na coxa... tão gostosas",
    "as covinhas que se formam no seu rosto quando você sorri",
    "o som do seu pipi...",
    "amo saber sobre seu dia, sobre oque comeu, oque fez", 
    "a sua existência",
    "quando você cuida de mim e me chama de neném",
    "o modo como você fica com vergonha quando eu falo que você é linda",
    "seu jeitinho meiga quando esta timida",
    "seu jeitinho de ser fofinha mesmo sem querer, dano aquele sorrisinho timido",
    "seus 'mais' no lugar de 'mas",
    "o modo como você sorri",
    "a forma como você se entrega pra mim",
    "o jeito que você faz eu me sentir especial e impotante",
    "pois você me ama mesmo com todos os meus defeitos",
    "pois voce me ama mesmo quando eu erro",
    "o jeito que você me faz ",
    "você ser minha melhor amiga",
    "você ser minha namorada",
    "você ser minha esposa",
    "você ser minha amante",
    "você ser minha submissa",
    "você ser minha putinha",
    "como você se preocupa comigo",
    "seu sotaquezinho maravilhoso",
    "o seu sorriso que me faz sorrir tbm",
    "o modo como você me desarma e me faz virar um menininho",
    "o seu modo de falar e sorrir",
    "sua fofurinhaaaaaaaaa linda do papi",
    "sua submissão",
    "seu jeito de me chamar de 'amor'",
    "o jeito q oc morre no bloodstrike ksksksk",
    "quando você me chama de papi",
    "o jeito que você me chama de 'meu dono'",
    "sua cintura...",
    "sua raba gostosa",
    "seus peitos",
    "seu umbiguinho maravilhoso",
    "o jeitinho que você se esforça",
    "o jeito que você me olha",
    "sua rebolada... dlc",
    "seu cabelo encaracolado",
    "seu cabelo liso",
    "seus olhares fofos kskssk",
    "cada 'uhum uhum' seu",
    "seu jeitinho de queimar a comida",
    "Seu jeito de me fazer sentir amado",
    "Seu jeito de me fazer sentir especial",
    "Seu jeito de me fazer rir",
    "Seu jeito de ser",
    "Seu olhar",
    "Seu sorriso",
    "Seu jeito de cuidar dos outros",
    "Sua risada contagiante",
    "Sua inteligência",
    "Como você escuta de verdade",
    "Seu carinho nos pequenos gestos",
    "Sua voz",
    "Seu olhar sincero",
    "Sua paciência",
    "Seu senso de humor",
    "Sua honestidade",
    "Como você me entende",
    "Sua criatividade",
    "Seu estilo único",
    "Seu entusiasmo pela vida",
    "Sua coragem",
    "Seu amor por animais (tirando a python amarela)",
    "Sua forma de ver o mundo",
    "Seu jeito de dançar... aquela rebolada...",
  ];

  for (let i = 0; i < 147; i++) {
    const item = document.createElement("li");
    const texto = coisasQueGosto[i % coisasQueGosto.length];
    item.textContent = `${i + 1}. ${texto}`;
    lista.appendChild(item);
  }
}
