const senhaCorreta = "eu"; 

function verificarSenha() {
  const senhaDigitada = document.getElementById("senha").value;
  const erro = document.getElementById("erro");

  if (senhaDigitada === senhaCorreta) {
    document.getElementById("login-container").style.display = "none";
    document.getElementById("conteudo").style.display = "block";
    gerarLista();
  } else {
    erro.textContent = "Como que você não sabe a senha?";
  }
}

function gerarLista() {
  const lista = document.getElementById("lista-carinho");

  const coisasQueGosto = [
    "Eu amo repetir oque você fala",
    "Eu amo a capacidade que você tem de me fazer te amar intensamente",
    "Eu amo o nosso namoro e o nosso casamento",
    "Eu amo não ser um casal normal",
    "Eu amo a nossa fofura",
    "Eu amo falar fofinho com oc e ouvir vc toda neném comigo",
    "Eu amo como mudei por você",
    "Eu amo como perdemos nosso orgulho apenas para ficar bem",
    "Eu amo como a gente nunca briga",
    "Eu amo como você sempre tem a forma mais fofa de fazer as coisas",
    "Eu amo como nossa confiança nunca deixou abalar nosso relacionamento",
    "Eu amo como você me cuida quando estou sensível",
    "Eu amo seus boas noites",
    "Eu amo seus bons dias",
    "Eu amo como você me da um motivo para eu te amar mais todos os dias",
    "Eu amo como gosto de dizer que te amo toda hora",
    "Eu amo quando você diz que me ama em horas inesperadas",
    "Eu amo nossos assuntos",
    "Eu amo como você me impressiona e ama meus elogios meu neném",
    "Eu amo como você consegue ser tudo o que preciso",
    "Eu amo como você não precisa de esforço pra me fazer feliz",
    "Eu amo precisar de você",
    "Eu amo quando acordo no meio da madrugada pensando em você",
    "Eu amo como você me trata diferente dos outros",
    "Eu amo como você fez eu confiar em você, para estar contigo ate hoje",
    "Eu amo amar tudo em você",
    "Eu gosto de reparar nos seus detalhes",
    "Eu amo como você faz meu olho brilhar",
    "Eu amo como eu choro por amar você",
    "Eu amo como você faz meu coração bater mais depressa",
    "Eu amo seu jeito protetor",
    "Eu amo como você faz eu me sentir homem",
    "Eu amo quando você me da a certeza de que me ama",
    "Eu amo quando você me da a certeza de que sou único",
    "Eu amo sua respiração",
    "Eu amo sua respiração ofegante...",
    "Eu amo como você morde os lábios",
    "Eu amo o seu queixo",
    "Eu amo a sua bochecha",
    "Eu amo receber mensagem sua",
    "Eu amo a sua letra",
    "Eu amo seus desenhos",
    "Eu amo ver aquele R no seu peito",
    "Eu amo a sua barriga",
    "Eu amo seu pé",
    "Eu amo todas as partes do seu corpo",
    "Eu amo a sua alegria",
    "Eu amo a sua carência",
    "Eu amo como você me fazer de desentendido só pra ouvir vc se explicar",
    "Eu amo quando começo as dizer as coisas que mais amo em ti, e você fica quieto só para ouvir mais coisas",
    "Eu amo as suas manias",
    "Eu amo como me sinto mal, quando oc tá triste",
    "Eu amo a cor do seu olhowe",
    "Eu amo o brilho dos seus olhos",
    "Eu amo quando você se rende a mim",
    "Eu amo como você repara em pequenos detalhes meu",
    "Eu amo como você me mima",
    "Eu amei escolher suas roupas",
    "Eu amo como você pretende criar um zoológico comigo",
    "Eu amo sua perfeição",
    "Eu amo as suas respostas",
    "Eu amo quando você concorda com minhas idéias loucas",
    "Eu amo quando você faz algo, só porque eu disse amar tal coisa",
    "Eu amo a nossa imaginação",
    "Eu amo viajar em pensamentos com você",
    "Eu amo o nosso jeito “criança”",
    "Eu amo o nosso jeito “maduro”",
    "Eu amo como aprendi a ser melhor, contigo",
    "Eu amo quando você tenta fingir que está brava",
    "Eu amo sua cara de safada",
    "Eu amo te xingar de minha puta",
    "Eu amo quando você fala 'andante' ou coisas com ante no final",
    "Eu amo quando você me liga de madrugada",
    "Eu amo quando você me liga apenas para ouvir minha voz",
    "Eu amo quando me liga para saber se esta tudo bem",
    "Eu amo como você faz tudo ficar bem",
    "Eu gosto de dormir pensando em você",
    "Eu gosto de acordar pensando em você",
    "Eu gosto de olhar as horas iguais e pensar em você",
    "Eu amo sonhar com você",
    "Eu amo quando você torna um sonho meu em realidade",
    "Eu amo te admirar",
    "Eu amo como você me admira",
    "Eu amo como você me elogia",
    "Eu amo como pensamos até nos detalhes do nosso futuro",
    "Eu amo como pensamos até nos detalhes da nossa casa",
    "Eu amo como tudo acontece naturalmente qnd estou com oc",
    "Eu amo ser eu mesmo contigo",
    "Eu amo quando você sussurra em meu ouvido na call",
    "Eu amo quando você faz birrinha",
    "Eu amo passar mais de uma hora no telefone com você",
    "Eu amo os apelidos carinhosos que você coloca em mim",
    "Eu amo como existem N motivos para eu te amar",
    "Eu amo você ser MINHA mulher",
    "Eu amo quando eu falo demais, e mesmo assim você me ouve com atenção",
    "Eu amo ter importância na sua vida",
    "Eu amo você ter total importância na minha vida",
    "Eu amo o nosso amor não ter medidas",
    "Eu amo como seu coração acelera quando falo sobre meu sentimento",
    "Eu amo como nosso amor pode preencher o universo",
    "Eu amo como se dividir o nosso amor para todos os casais que existem no mundo, ainda assim, ele seria o suficiente",
    "Eu amo como você é mais do que eu esperava pra ser ‘o amor da minha vida’",
    "Eu amo como nunca encontro palavras pra expressar esse sentimento",
    "Eu amo te querer",
    "Eu amo não precisar viver sem você",
    "Eu amo você ter aparecido no momento em que eu mais precisei",
    "Eu amo ter me guardado pra oc",
    "Eu amo a certeza de que você nunca irá me perder",
    "Eu amo a segurança de que vou te ter sempre comigo",
    "Eu amo olhar pra alguma roupa feminina e te imaginar nela",
    "Eu amo como você é minha inspiração",
    "Eu amo como durante esses meses juntos, eu não tive duvida, sequer um dia, se é realmente você, que e quero pra toda minha vida",
    "Eu amo como minha necessidade de você aumenta conforme o tempo que passamos juntos",
    "Eu amo saber que nosso amor é sincero",
    "Eu amo saber que nosso amor não é frágil",
    "Eu amo como meu coração é apenas seu",
    "Eu amo saber que vamos conseguir enfrentar tudo",
    "Eu amo ter a certeza que você é o “Amor da minha vida”",
    "Eu amo como você me fez acreditar no amor",
    "Eu amo como você é minha, somente minha e toda minha.",
    "Eu amo você, apenas por ser você, sem precisar de motivos ou um porquê. Isso não tem explicação, não tem definição, é amor ou talvez mais que isso. É intenso, é puro, é real … Eu amo cada detalhe seu. ",
    "Eu amo como com você eu me sinto capaz de qualquer coisa",
    "Eu amo as suas brincadeiras",
    "Eu amo os seus dentes",
    "Eu amo como você planeja o nosso futuro",
    "Eu amo como você esta em todos os meus planos",
    "Eu amo confiar em você e poder contar tudo pra oc",
    "Eu amo passar cada segundo do meu dia pesando em você",
    "Eu amo estar com saudade segundos depois de me despedir você",
    "Eu amo seu corte na orelha, acho ele legal",
    "Eu amo quando você tenta me irritar",
    "Eu amo o seu jeito bobo",
    "Eu amo quando você me provoca",
    "Eu amo quando você diz que vai lamber meu pau olhando pra mim",
    "Eu amo a sua língua",
    "Eu amo ter você",
    "Eu amo ser seu",
    "Eu amo a sua beleza maior que a de qualquer modelo",
    "Eu amo te fazer rir",
    "Eu amo como sempre abro um sorriso quando te escuto",
    "Eu amo como depois de tanto tempo sou completamente apaixonado por você",
    "Eu amo ficar bobo com você, rs.",
    "Eu amo como você arruma o cabelo",
    "Eu amo como você olha pra mim quando ligo a cam",
    "Eu amo cada segundo que eu passo contigo mesmo de longe",
    "Eu amo falar as coisas que amo em você",
    "Eu amo a sua capacidade de me fazer rir em qualquer situação",
    "Eu amo a sua ironia",
    "Eu amo como você me respeita",
    "Eu amo respeitar e admirar você",
    "Eu amo como você me tornou romântico",
    "Eu amo como te faço ficar sem argumentos",
    "Eu amo como você perde a linha hhihihihihi",
    "Eu amo a segurança que você me transmite",
    "Eu amo a sua demora pra se arrumar",
    "Eu amo a sua vaidade",
    "Eu amo como você me ama até na TPM",
    "Eu amo quando você faz a coisa que eu falo que eu amo (você entendeu rs)",
    "Eu amo pedir sua opinião pra tudo",
    "Eu amo como você pede minha opinião pra tudo",
    "Eu amo como você é o meu futuro",
    "Eu amo como você me acha bonito mesmo desarrumado",
    "Eu amo os seus dedos",
    "Eu amo os seus baby dolls...",
    "Eu amo como você admite seus erros",
    "Eu amo como você pede desculpa quando está errado",
    "Eu amo como você às vezes fala nada com nada",
    "Eu amo como nunca quero deixá-la ir",
    "Eu amo como odeio ficar longe de você",
    "Eu amo meu medo de te perder",
    "Eu amo sentir ciúme de você",
    "Eu amo te dar carinho",
    "Eu amo como oc eh a menininha do papai",
    "Eu amo as suas piadas sem graça",
    "amo jogar com você",
    "amo nossos momentos em call",
    "amo sua forma de cuidar de você",
    "amo a sua fidelidade mb",	
    "amo a sua lealdade",
    "Eu te amo porque até eu me amo mais depois que te conheci",
    "Eu te amo porque você sempre quer ser melhor e me dar o melhor",
    "Eu te amo porque juntos fazemos loucuras maravilhosas",
    "Eu te amo porque sim",
    "Eu te amo porque você me envia os melhores stickers e figurinhas",
    "eu amo pensar em você e no seu jeitinho e pensar: encontrei",
    "eu te amo pq oc faz eu rir ate doer as bochechas",
    "amo seu jeito de ser",
    "te amo por você ser a melhor esposa do mundo"/
    "te amo por você ser a melhor namorada do mundo",
    "amo quando você fala sobre ter filhos",	
    "amo o quanto você se importa com nossa relação",
    "amo o quanto você se esforça para me agradar",
    "amo quando você demonstra oque sente por mim",
    "amo seu narizinho fofinho'",
    "amo ver vc sem oculos",
    "seu narizinho lindinho meu amor",
    "o formato dos seus labios que me atraem tanto...",
    "seu sorriso bobinho hihihihihi",
    "todas coisas que sairem de você exceto o milho... ",
    "eu amo seus defeitos amor, todinhos",
    "a suas marcas na coxa... tão gostosas",
    "as covinhas que se formam no seu rosto quando você sorri",
    "o som do seu pipi...",
    "amo saber sobre seu dia, sobre oque comeu, oque fez", 
    "a sua existência",
    "quando você cuida de mim e me chama de neném",
    "o modo como você fica com vergonha quando eu falo que você é linda",
    "seu jeitinho meiga quando esta timida",
    "seu jeitinho de ser fofinha mesmo sem querer, dano aquele sorrisinho timido",
    "seus 'mais' no lugar de 'mas",
    "o modo como você sorri",
    "a forma como você se entrega pra mim",
    "o jeito que você faz eu me sentir especial e importante",
    "pois você me ama mesmo com todos os meus defeitos",
    "pois voce me ama mesmo quando eu erro",
    "o jeito que você me faz gozar",
    "você ser minha melhor amiga",
    "você ser minha namorada",
    "você ser minha esposa",
    "você ser minha amante",
    "você ser minha submissa",
    "você ser minha putinha",
    "como você se preocupa comigo",
    "seu sotaquezinho maravilhoso",
    "o seu sorriso que me faz sorrir tbm",
    "o modo como você me desarma e me faz virar um menininho",
    "o seu modo de falar e sorrir",
    "sua fofurinhaaaaaaaaa linda do papi",
    "sua submissão",
    "seu jeito de me chamar de 'amor'",
    "o jeito q oc morre no bloodstrike ksksksk",
    "quando você me chama de papi",
    "o jeito que você me chama de 'meu dono'",
    "sua cintura...",
    "sua raba gostosa",
    "seus peitos",
    "seu umbiguinho maravilhoso",
    "o jeitinho que você se esforça",
    "o jeito que você me olha",
    "sua rebolada... dlc",
    "seu cabelo encaracolado",
    "seu cabelo liso",
    "seus olhares fofos kskssk",
    "cada 'uhum uhum' seu",
    "seu jeitinho de queimar a comida",
    "Seu jeito de me fazer sentir amado",
    "Seu jeito de me fazer sentir especial",
    "Seu jeito de me fazer rir",
    "Seu jeito de ser",
    "Seu olhar",
    "Seu sorriso",
    "Seu jeito de cuidar dos outros",
    "Sua risada contagiante",
    "Sua inteligência",
    "Como você escuta de verdade",
    "Seu carinho nos pequenos gestos",
    "Sua voz",
    "Seu olhar sincero",
    "Sua paciência",
    "Seu senso de humor",
    "Sua honestidade",
    "Como você me entende",
    "Sua criatividade",
    "Seu estilo único",
    "Seu entusiasmo pela vida",
    "Sua coragem",
    "Seu amor por animais (tirando a python amarela)",
    "Sua forma de ver o mundo",
    "Seu jeito de dançar... aquela rebolada...",
  ];

  for (let i = 0; i < 269; i++) {
    const item = document.createElement("li");
    const texto = coisasQueGosto[i % coisasQueGosto.length];
    item.textContent = `${i + 1}. ${texto}`;
    lista.appendChild(item);
  }
}
